// This file is auto-generated by AnimationClipEventKeyStringGenerator.cs
// Do not modify this file directly. Changes will be overwritten.
namespace Cat
{
	public static class AnimationEventKeys
	{
		public const string PlayFX = "PlayFX";
		public const string PlaySFX = "PlaySFX";
		public const string Sleep = "Sleep";
		public const string ActionStart = "ActionStart";
		public const string LoopStart = "LoopStart";
		public const string LoopEnd = "LoopEnd";
		public const string ShowEquipItem = "ShowEquipItem";
		public const string HideEquipItem = "HideEquipItem";
		public const string EyeControl = "EyeControl";
		public const string Effect = "Effect";
	}
}
